development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:7ae9a0731e1140194f865afce58578b0@barreleye.redistogo.com:10585/
  # url: redis://localhost:6379/1
